name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9

    steps:
      - name: Install Python via conda.
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python-version }}
          conda-channels: defaults,bioconda,conda-forge
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install test dependencies via pip
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: pytest
      - name: Create text report
        run: coverage report
      - name: Create XML report for codacy
        run: coverage xml

